### ISSUE TITLE
Proposal - Work plan

### ISSUE THREAD

**Issue by GabrielBogo** [UBC-MDS/CrimeVisualizer#1]
- [x] Section 1 - Overview (@GabrielBogo)
- [x] Section 2 - Description of the Data (@GabrielBogo, @olivia-lin)
- [x] Section 3 - Usage scenario and Tasks (@GabrielBogo)
- [x] Section 4: Description of your app & sketch(@olivia-lin)

**Comment by GabrielBogo** [comment]
Done.
