### ISSUE TITLE
# To-Do list Milestone 3

### ISSUE THREAD

**Issue by GabrielBogo** [UBC-MDS/CrimeVisualizer#17]
- [ ] Add link to deployed app in the README
- [ ] Add link with feedback issues in the README
- [ ] Improve feedback for Group 1
- [ ] Write new Writeup

Shiny App Improvements
- [ ] Add a good title to the plots
- [ ] Overlay plot of State average
- [ ] Implement stacked column chart
  - [ ] Make dataset tidy
  - [ ] Change wrangling in Shiny app
  - [ ] Change ggplot in Shiny App
- [ ] Remove comma from years in slide bar
